"""initial version

Revision ID: cadbab16466b
Revises: 
Create Date: 2024-11-10 00:01:11.397002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cadbab16466b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create workout_plans first
    op.create_table('workout_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('days', sa.JSON(), nullable=True),
        sa.Column('exercises', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Then create users
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('telegram_id', sa.BigInteger(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('current_workout_plan_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['current_workout_plan_id'], ['workout_plans.id'], deferrable=True, initially='DEFERRED'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('telegram_id')
    )

    # Add foreign key to workout_plans after users exists
    op.create_foreign_key(None, 'workout_plans', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # Finally create lift_records
    op.create_table('lift_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('exercise', sa.String(), nullable=True),
        sa.Column('weight', sa.Integer(), nullable=True),
        sa.Column('reps', sa.Integer(), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lift_records')
    op.drop_table('workout_plans')
    op.drop_table('users')
    # ### end Alembic commands ###
